export type DemoTrainCategory =
  | 'talgo'
  | 'standard'
  | 'private_standard'
  | 'international';

export type DemoTrainDefinition = {
  pair: string;
  routeLabel: string;
  origin: string;
  destination: string;
  category: DemoTrainCategory;
  categoryLabel: string;
  periodicity: string;
  compositions: string;
  wagonCount: number;
  carrier: string;
  tractionType: 'electric' | 'diesel';
};

export const DEMO_TRAIN_DEFINITIONS: DemoTrainDefinition[] = [
  {
    pair: '1/2',
    routeLabel: 'Алматы-2 – Ташкент',
    origin: 'Алматы-2',
    destination: 'Ташкент',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 29,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '3/4',
    routeLabel: 'Нурлы жол – Алматы-2',
    origin: 'Нурлы жол',
    destination: 'Алматы-2',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 29,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '9/10',
    routeLabel: 'Астана-1 – Алматы-2',
    origin: 'Астана-1',
    destination: 'Алматы-2',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 31,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '11/12',
    routeLabel: 'Алматы-2 – Шымкент',
    origin: 'Алматы-2',
    destination: 'Шымкент',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 31,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '85/86',
    routeLabel: 'Нурлы жол – Шымкент',
    origin: 'Нурлы жол',
    destination: 'Шымкент',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 31,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '25/26',
    routeLabel: 'Алматы-2 – Шымкент',
    origin: 'Алматы-2',
    destination: 'Шымкент',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 27,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '71/72',
    routeLabel: 'Нур-Султан НЖ – Шымкент',
    origin: 'Нур-Султан НЖ',
    destination: 'Шымкент',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 27,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '27/28',
    routeLabel: 'Алматы-2 – Уральск',
    origin: 'Алматы-2',
    destination: 'Уральск',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 29,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '105/106',
    routeLabel: 'Алматы-2 – Петропавловск',
    origin: 'Алматы-2',
    destination: 'Петропавловск',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'через день',
    compositions: '3 состава',
    wagonCount: 23,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '119/120',
    routeLabel: 'Алматы-2 – Костанай',
    origin: 'Алматы-2',
    destination: 'Костанай',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'через день',
    compositions: 'кольцовка',
    wagonCount: 23,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '66/65',
    routeLabel: 'Нурлы жол – Кызылорда',
    origin: 'Нурлы жол',
    destination: 'Кызылорда',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'через день',
    compositions: '1 состав',
    wagonCount: 23,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '81/82',
    routeLabel: 'Нурлы жол – Орал',
    origin: 'Нурлы жол',
    destination: 'Орал',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 23,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '67/68',
    routeLabel: 'Нурлы жол – Оскемен-1',
    origin: 'Нурлы жол',
    destination: 'Оскемен-1',
    category: 'talgo',
    categoryLabel: 'Тальго',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 31,
    carrier: 'АО ПП',
    tractionType: 'electric',
  },
  {
    pair: '21/22',
    routeLabel: 'Кызылорда – Семей',
    origin: 'Кызылорда',
    destination: 'Семей',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '4 состава',
    wagonCount: 16,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '23/24',
    routeLabel: 'Актобе – Алматы-1',
    origin: 'Актобе',
    destination: 'Алматы-1',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '31/32',
    routeLabel: 'Павлодар – Алматы-2',
    origin: 'Павлодар',
    destination: 'Алматы-2',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '3 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '33/34',
    routeLabel: 'Актобе – Алматы-1',
    origin: 'Актобе',
    destination: 'Алматы-1',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '4 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '37/38',
    routeLabel: 'Мангистау – Семей',
    origin: 'Мангистау',
    destination: 'Семей',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'через день',
    compositions: '3 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '41/42',
    routeLabel: 'Атырау – Алматы-1',
    origin: 'Атырау',
    destination: 'Алматы-1',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '5 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '45/46',
    routeLabel: 'Павлодар – Туркестан',
    origin: 'Павлодар',
    destination: 'Туркестан',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '4 состава',
    wagonCount: 22,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '47/48',
    routeLabel: 'Атырау – Нурлы жол',
    origin: 'Атырау',
    destination: 'Нурлы жол',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '73/74',
    routeLabel: 'Алматы-2 – Жезказган',
    origin: 'Алматы-2',
    destination: 'Жезказган',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 14,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '88/87',
    routeLabel: 'Алматы-2 – Сарыагаш',
    origin: 'Алматы-2',
    destination: 'Сарыагаш',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'через день',
    compositions: 'кольцовка',
    wagonCount: 14,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '77/78',
    routeLabel: 'Алматы-2 – Мангистау',
    origin: 'Алматы-2',
    destination: 'Мангистау',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '5 составов',
    wagonCount: 22,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '139/140',
    routeLabel: 'Павлодар – Пресногорьковская',
    origin: 'Павлодар',
    destination: 'Пресногорьковская',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'через день',
    compositions: '1 состав',
    wagonCount: 6,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '313/314',
    routeLabel: 'Мангистау – Атырау',
    origin: 'Мангистау',
    destination: 'Атырау',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '4 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '692/691',
    routeLabel: 'Актобе – Атырау',
    origin: 'Актобе',
    destination: 'Атырау',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: 'кольцовка',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '351/352',
    routeLabel: 'Алматы-2 – Оскемен-1',
    origin: 'Алматы-2',
    destination: 'Оскемен-1',
    category: 'standard',
    categoryLabel: 'Стандартные',
    periodicity: 'ежедневно',
    compositions: '3 состава',
    wagonCount: 18,
    carrier: 'АО ПП',
    tractionType: 'diesel',
  },
  {
    pair: '15/16',
    routeLabel: 'Алматы – Петропавловск',
    origin: 'Алматы',
    destination: 'Петропавловск',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 17,
    carrier: 'ТОО Турксиб Астана',
    tractionType: 'diesel',
  },
  {
    pair: '43/44',
    routeLabel: 'Костанай – Алматы',
    origin: 'Костанай',
    destination: 'Алматы',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'ежедневно',
    compositions: '4 состава',
    wagonCount: 21,
    carrier: 'ТОО Сары-Арка Компани',
    tractionType: 'diesel',
  },
  {
    pair: '57/58',
    routeLabel: 'Уральск – Нур-Султан НЖ',
    origin: 'Уральск',
    destination: 'Нур-Султан НЖ',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 19,
    carrier: 'ТОО Arlan Trans Astana',
    tractionType: 'diesel',
  },
  {
    pair: '76/75',
    routeLabel: 'Кызылорда – Петропавловск',
    origin: 'Кызылорда',
    destination: 'Петропавловск',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 15,
    carrier: 'ТОО Arlan Trans Astana',
    tractionType: 'diesel',
  },
  {
    pair: '107/108',
    routeLabel: 'Жезказган – Нур-Султан НЖ',
    origin: 'Жезказган',
    destination: 'Нур-Султан НЖ',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'ежедневно',
    compositions: '2 состава',
    wagonCount: 17,
    carrier: 'ТОО Марал Нур',
    tractionType: 'diesel',
  },
  {
    pair: '117/118',
    routeLabel: 'Кызылорда – Павлодар',
    origin: 'Кызылорда',
    destination: 'Павлодар',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 17,
    carrier: 'ТОО Марал Нур',
    tractionType: 'diesel',
  },
  {
    pair: '122/121',
    routeLabel: 'Нур-Султан НЖ – Семей',
    origin: 'Нур-Султан НЖ',
    destination: 'Семей',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'ежедневно',
    compositions: '4 состава',
    wagonCount: 17,
    carrier: 'ТОО Арай Транс KZ',
    tractionType: 'diesel',
  },
  {
    pair: '327/328',
    routeLabel: 'Костанай – Караганды',
    origin: 'Костанай',
    destination: 'Караганды',
    category: 'private_standard',
    categoryLabel: 'Частные стандартные',
    periodicity: 'ежедневно',
    compositions: '3 состава',
    wagonCount: 11,
    carrier: 'ТОО Турксиб Астана',
    tractionType: 'diesel',
  },
  {
    pair: '7/8',
    routeLabel: 'Алматы-2 – Саратов',
    origin: 'Алматы-2',
    destination: 'Саратов',
    category: 'international',
    categoryLabel: 'Международные',
    periodicity: 'через день',
    compositions: '3 состава',
    wagonCount: 18,
    carrier: 'КТЖ',
    tractionType: 'electric',
  },
  {
    pair: '301/302',
    routeLabel: 'Алматы-2 – Новосибирск',
    origin: 'Алматы-2',
    destination: 'Новосибирск',
    category: 'international',
    categoryLabel: 'Международные',
    periodicity: 'через день',
    compositions: '2 состава',
    wagonCount: 18,
    carrier: 'КТЖ',
    tractionType: 'electric',
  },
  {
    pair: '305/306',
    routeLabel: 'Ташкент – Москва',
    origin: 'Ташкент',
    destination: 'Москва',
    category: 'international',
    categoryLabel: 'Международные',
    periodicity: '2 раза в нед.',
    compositions: '4 состава',
    wagonCount: 11,
    carrier: 'УЗБ',
    tractionType: 'electric',
  },
  {
    pair: '123/124',
    routeLabel: 'Ташкент – Ургенч – Волгоград',
    origin: 'Ташкент',
    destination: 'Волгоград',
    category: 'international',
    categoryLabel: 'Международные',
    periodicity: '2 раза в нед.',
    compositions: '2 состава',
    wagonCount: 14,
    carrier: 'УЗБ',
    tractionType: 'electric',
  },
  {
    pair: '319/320',
    routeLabel: 'Куляб – Волгоград',
    origin: 'Куляб',
    destination: 'Волгоград',
    category: 'international',
    categoryLabel: 'Международные',
    periodicity: '1 раз в нед.',
    compositions: '2 состава',
    wagonCount: 11,
    carrier: 'ТАДЖ',
    tractionType: 'electric',
  },
  {
    pair: '329/330',
    routeLabel: 'Душанбе – Волгоград',
    origin: 'Душанбе',
    destination: 'Волгоград',
    category: 'international',
    categoryLabel: 'Международные',
    periodicity: '1 раз в нед.',
    compositions: '2 состава',
    wagonCount: 11,
    carrier: 'ТАДЖ',
    tractionType: 'electric',
  },
];

export const DEMO_FALLBACK_STOPS: Record<string, string[]> = {
  '001/002': ['Алматы-2', 'Шу', 'Тараз', 'Шымкент', 'Сарыагаш', 'Ташкент'],
  '007/008': ['Алматы-2', 'Караганда', 'Костанай', 'Троицк', 'Самара', 'Саратов'],
  '301/302': ['Алматы-2', 'Семей', 'Павлодар', 'Барнаул', 'Новосибирск'],
  '305/306': ['Ташкент', 'Шымкент', 'Кызылорда', 'Актобе', 'Самара', 'Москва'],
  '123/124': ['Ташкент', 'Самарканд', 'Ургенч', 'Атырау', 'Астрахань', 'Волгоград'],
  '319/320': ['Куляб', 'Душанбе', 'Ташкент', 'Атырау', 'Астрахань', 'Волгоград'],
  '329/330': ['Душанбе', 'Ташкент', 'Кызылорда', 'Актобе', 'Астрахань', 'Волгоград'],
};
